up:
	@echo "runing the coffee house ..."
	uvicorn main_schema:app --reload

env:
	@echo "activate the coffee house env ..."
	source ~/Desktop/env/env_the_coffee_house_api/bin/activate; \

create_db:
	@echo "creating database for pgadmin4 ..."
	python3 database.py
